<a href="https://colab.research.google.com/github/ritzz19/Bank_churn_ANN/blob/master/ANN_Bank.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#importing the libraries 
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [0]:
#importing the datasets
dataset=pd.read_csv('Churn_Modelling.csv')
X=dataset.iloc[:,3:13].values
y=dataset.iloc[:,13].values

In [0]:
#Encoding categorical dataset
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder_X_1=LabelEncoder()
X[:, 1]=labelencoder_X_1.fit_transform(X[:,1])
labelencoder_X_2=LabelEncoder()
X[:, 2]=labelencoder_X_2.fit_transform(X[:,2])
onehotencoder=OneHotEncoder(categorical_features=[1])
X=onehotencoder.fit_transform(X).toarray()
X=X[:,1:]

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [0]:
#Splitting the dataset into training and testing set
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.35,random_state=0)

In [0]:
#Feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

Making ANN

In [0]:
#Importing the keras libraries
import keras
from keras.models import Sequential #initialize inputs
from keras.layers import Dense #create layers in ANN(Hidden layers)
from keras.layers import Dropout #for avoiding overfitting

In [0]:
#Initialising the ANN
classifier=Sequential()

In [0]:
#Adding the input layer and first hidden layer
classifier.add(Dense(output_dim=6,init='uniform',activation='relu',input_dim=11))
classifier.add(Dropout(p=0.1))


Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.1)`
  


In [0]:
#Adding the second hidden layer
classifier.add(Dense(output_dim=6,init='uniform',activation='relu'))
classifier.add(Dropout(p=0.1))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.1)`
  


In [0]:
#Adding the output layer
classifier.add(Dense(output_dim=1,init='uniform',activation='sigmoid'))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [0]:
#Compiling the ANN
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [0]:
#Fitting the ANN to the training set
classifier.fit(X_train,y_train, batch_size=10, nb_epoch=100)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Epoch 1/100
6500/6500 [==============================] - 1s 138us/step - loss: 0.5017 - acc: 0.7972
Epoch 2/100
6500/6500 [==============================] - 1s 104us/step - loss: 0.4305 - acc: 0.7975
Epoch 3/100
6500/6500 [==============================] - 1s 105us/step - loss: 0.4269 - acc: 0.7975
Epoch 4/100
6500/6500 [==============================] - 1s 105us/step - loss: 0.4235 - acc: 0.7975
Epoch 5/100
6500/6500 [==============================] - 1s 105us/step - loss: 0.4200 - acc: 0.7977
Epoch 6/100
6500/6500 [==============================] - 1s 107us/step - loss: 0.4175 - acc: 0.8226
Epoch 7/100
6500/6500 [==============================] - 1s 106us/step - loss: 0.4157 - acc: 0.8263
Epoch 8/100
6500/6500 [==============================] - 1s 109us/step - loss: 0.4148 - acc: 0.8260
Epoch 9/100
6500/6500 [==============================] - 1s 106us/step - loss: 0.4134 - acc: 0.8285
Epoch 10/100
6500/6500 [==============================] - 1s 112us/step - loss: 0.4124 - acc: 0.8300

### Making the predictions and evaluating the model

In [0]:
#Predicting the test set results
y_pred=classifier.predict(X_test)
y_pred=(y_pred>0.5)

In [0]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [0]:
#Making the confusion matix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, y_pred)

In [0]:
cm

array([[2691,   88],
       [ 471,  250]])

Predicting
1.Geography:France
2.Credit score: 600
3.Gender: Male
4.Age: 40 years old
5.Tenture: 3 years
6.Balance: $60000
7.Number of products: 2
8.Does this customer have a credit card?: Yes
9.Is this customer an ative member: Yes
10.Estimates Salary= $50000 

In [0]:
new_prediction = classifier.predict(sc.transform(np.array([[0, 0, 600, 1, 40, 3, 60000, 2,1,1, 50000]])))
new_prediction=(new_prediction>0.5)

In [0]:
new_prediction

array([[False]])

# Evaluating, Improving and Tuning ANN

In [0]:
# Evaluating the ANN
from keras.wrappers.scikit_learn import KerasClassifier #combining keras and scikit learn
from sklearn.model_selection import cross_val_score
def build_classifier(): #kerasClassifier expect one of its arument as function Build the architecture of our ANN)
  classifier=Sequential()
  classifier.add(Dense(output_dim=6,init='uniform',activation='relu',input_dim=11))
  classifier.add(Dense(output_dim=6,init='uniform',activation='relu'))
  classifier.add(Dense(output_dim=1,init='uniform',activation='sigmoid'))
  classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
  return classifier
classifier = KerasClassifier(build_fn = build_classifier, batch_size=10,nb_epoch=100) #global
accuracies=cross_val_score(estimator=classifier, X=X_train, y=y_train,cv=10,n_jobs=-1)
mean=accuracies.mean()
variance=accuracies.std()
  

In [0]:
mean

0.7975384582006014

In [0]:
#Improving the ANN


In [0]:
#Tuning the ANN
from keras.wrappers.scikit_learn import KerasClassifier #combining keras and scikit learn
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
def build_classifier(optimizer): #kerasClassifier expect one of its arument as function Build the architecture of our ANN)
  classifier=Sequential()
  classifier.add(Dense(output_dim=6,init='uniform',activation='relu',input_dim=11))
  classifier.add(Dense(output_dim=6,init='uniform',activation='relu'))
  classifier.add(Dense(output_dim=1,init='uniform',activation='sigmoid'))
  classifier.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])
  return classifier
classifier = KerasClassifier(build_fn = build_classifier) #global
parameters = {'batch_size':[25,32],
              'nb_epoch':[100,500],
              'optimizer':['adam','rmsprop']}
grid_search=GridSearchCV(estimator=classifier,
                         param_grid=parameters,
                         scoring='accuracy',
                         cv=10)
grid_search=grid_search.fit(X_train,y_train)
best_parameters=grid_search.best_params_
best_accuracy=grid_search.best_score_

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  import sys
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:8: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  if __name__ == '__main__':


Epoch 1/1
5850/5850 [==============================] - 6s 1ms/step - loss: 0.5833 - acc: 0.7993
Epoch 1/1
5850/5850 [==============================] - 6s 1ms/step - loss: 0.5725 - acc: 0.7959
Epoch 1/1
5850/5850 [==============================] - 6s 1ms/step - loss: 0.5906 - acc: 0.7957
Epoch 1/1
5850/5850 [==============================] - 6s 1ms/step - loss: 0.5750 - acc: 0.7950
Epoch 1/1
5850/5850 [==============================] - 7s 1ms/step - loss: 0.5816 - acc: 0.7971
Epoch 1/1
5850/5850 [==============================] - 7s 1ms/step - loss: 0.5694 - acc: 0.7985
Epoch 1/1
5850/5850 [==============================] - 7s 1ms/step - loss: 0.5875 - acc: 0.7988
Epoch 1/1
5850/5850 [==============================] - 7s 1ms/step - loss: 0.5676 - acc: 0.7976
Epoch 1/1
5850/5850 [==============================] - 7s 1ms/step - loss: 0.5980 - acc: 0.7964
Epoch 1/1
5850/5850 [==============================] - 7s 1ms/step - loss: 0.5711 - acc: 0.7969
Epoch 1/1
5850/5850 [===================